### PR TITLE
feat: remove logging implementation

### PR DESCRIPTION
**Pull request by b-zee**
Libraries should not setup a logging implementation.

This should be left to the applications or binaries that use the
library.

This will make sure applications do not get unexpected output on stdout
or stderr.

### CODE REVIEW

**Comment by b-zee** [comment]
I've encountered the same issue with some testing myself. I can hardly see any side effects, looking at the code changes, though. Really curious to see if someone else can spot something.

**Comment by dirvine** [comment]
Scanning the changes I don't see how this fails a test. I Will look deeper later. Perhaps @bochaco  might lend a hand. I know he's busy though

**Comment by bochaco** [comment]
Ah no, don't worry about that test failure right now, it's because we still have the sn-node issues since very recent changes with rewards.

**Review by bochaco — APPROVED** [review]
We'll need to have tests to initialise the logger as it's not done at the moment.

**Pull request merged**
